# OSX/Linux (https://github.com/travis-ci-tester/toolchain-table)

# Workaround for https://github.com/travis-ci/travis-ci/issues/8363
language:
  - minimal

# Container-based infrastructure (Linux)
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false

# Install packages differs for container-based infrastructure
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - python3-pip

      - g++-5
      - gcc-5

dist:
  - trusty

env:
  global:
    - secure: "fVN184/3nwAB7opE8h3rhBwWrMeX7LW15b4IJQE2zDW9MYfm6BW/S1fPdniyRiFQbW6fNK9m6IKtjmk0xjOq2f4Wu9ULfMu+AgnCwlX6aV7s8bA2mRBqtL9zNTAAX3XHzTMwHx9nCJjYyYScIq7ApJ68et88lCaWwGn+kLdE2AOuOZY/msE+W9SgTotXV6aBK2l0oXuT4ph+ysfT7n3kaSPDBG//amhCSGDnkjBdEA0cw6tdwfsY2gdQfdUGyzC77c5NegYQmu86MnLVT7VQwfn4/av59grCLHQ5xn7IDJitTrcM7njCsfJEAjAGCGjPOYj9PT6btMbBf3iMWp9PPRY7uiLCt07yVgyplBbvrJKHgXwqyo5uK6ei4oc2NdfYZ9vkAbzKFY+U2d27yX5iIBrXYaMQ3aD04rFGJ+Xvo3i70AMTqM3Tmy2/WC1KkIOngfM9g1+PjazHHgz7PyrQlhbOZmYpM0F82qzjVkrZA81ujBrQ1KMST9ZVJicxE3zNeuJjLAQhFerMLgJc3ntudmwxi8UqoGKKlazO6qdJT7VLITJ9gVB3m+1LRQzo6ZDqs9V9RCMaGIy2t4bN3PAgMWdEJDoU1zhuy2V2AgeQGFzG4eanpYZQqAp6poV02DjegvkXC7cA5QrIcGZKdrIXLQk4TBXx2ZVigDio5gYLyrY="

matrix:
  include:
    # Linux {
    - os: linux
      env: PROJECT_DIR=examples/Eigen TOOLCHAIN=default
    - os: linux
      env: PROJECT_DIR=examples/Eigen TOOLCHAIN=clang-libstdcxx
    - os: linux
      env: PROJECT_DIR=examples/Eigen TOOLCHAIN=gcc-5
    - os: linux
      env: PROJECT_DIR=examples/Eigen TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon
    - os: linux
      env: PROJECT_DIR=examples/Eigen TOOLCHAIN=android-ndk-r15c-api-21-armeabi-v7a-neon-clang-libcxx
    - os: linux
      env: PROJECT_DIR=examples/Eigen TOOLCHAIN=analyze
    - os: linux
      env: PROJECT_DIR=examples/Eigen TOOLCHAIN=sanitize-address
    - os: linux
      env: PROJECT_DIR=examples/Eigen TOOLCHAIN=sanitize-leak
    - os: linux
      env: PROJECT_DIR=examples/Eigen TOOLCHAIN=sanitize-thread
    # }

    # OSX {
    - os: osx
      env: PROJECT_DIR=examples/Eigen TOOLCHAIN=libcxx
    - os: osx
      osx_image: xcode8.2
      env: PROJECT_DIR=examples/Eigen TOOLCHAIN=xcode-cxx98
    - os: osx
      env: PROJECT_DIR=examples/Eigen TOOLCHAIN=osx-10-12
    - os: osx
      env: PROJECT_DIR=examples/Eigen TOOLCHAIN=ios-nocodesign-10-3
    # }

    # Extra for OpenCV {
    - os: osx
      env: PROJECT_DIR=examples/Eigen TOOLCHAIN=ios-nocodesign-10-3-arm64
    - os: osx
      env: PROJECT_DIR=examples/Eigen TOOLCHAIN=ios-nocodesign-10-3-armv7
    - os: osx
      osx_image: xcode9
      env: PROJECT_DIR=examples/Eigen TOOLCHAIN=ios-nocodesign-11-0-arm64-dep-9-0-device-libcxx-hid-sections
    # }

install:
  # Info about OS
  - uname -a

  # Disable autoupdate
  # * https://github.com/Homebrew/brew/blob/7d31a70373edae4d8e78d91a4cbc05324bebc3ba/Library/Homebrew/manpages/brew.1.md.erb#L202
  - export HOMEBREW_NO_AUTO_UPDATE=1

  # Install Python 3
  - if [[ "`uname`" == "Darwin" ]]; then travis_retry brew install python3; fi

  # Install Python package 'requests'
  # 'easy_install3' is not installed by 'brew install python3' on OS X 10.9 Maverick
  - if [[ "`uname`" == "Darwin" ]]; then pip3 install requests; fi
  - if [[ "`uname`" == "Linux" ]]; then travis_retry pip3 install --user requests; fi

  # Install latest Polly toolchains and scripts
  - wget https://github.com/ruslo/polly/archive/master.zip
  - unzip master.zip
  - POLLY_ROOT="`pwd`/polly-master"
  - export PATH="${POLLY_ROOT}/bin:${PATH}"

  # Install dependencies (CMake, Android NDK)
  - install-ci-dependencies.py

  # Tune locations
  - export PATH="`pwd`/_ci/cmake/bin:${PATH}"

  # Installed if toolchain is Android (otherwise directory doesn't exist)
  - export ANDROID_NDK_r10e="`pwd`/_ci/android-ndk-r10e"
  - export ANDROID_NDK_r11c="`pwd`/_ci/android-ndk-r11c"
  - export ANDROID_NDK_r15c="`pwd`/_ci/android-ndk-r15c"
  - export ANDROID_NDK_r16b="`pwd`/_ci/android-ndk-r16b"

script:
  - python3 ./jenkins.py --upload

# https://docs.travis-ci.com/user/customizing-the-build/#Whitelisting-or-blacklisting-branches
# Exclude branch 'pkg.template'. Nothing to build there.
branches:
  except:
    - pkg.template
    - /^pr\..*/
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/
