# OSX/Linux (https://github.com/travis-ci-tester/toolchain-table)

language:
  - cpp

os:
  - linux
  - osx

# Container-based infrastructure (Linux)
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false

# Install packages differs for container-based infrastructure
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F
# * http://stackoverflow.com/a/30925448/2288008
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - python3

      # python3-pip package is not available, use 'easy_install3':
      # * https://github.com/travis-ci/apt-package-whitelist/issues/768
      - python3-setuptools # easy_install3

      # https://github.com/travis-ci-tester/travis-test-clang-cxx-11
      - libstdc++-4.8-dev

      # https://github.com/travis-ci-tester/travis-test-gcc-cxx-11
      - g++-4.8

env:
  - PROJECT_DIR=examples/Foo TOOLCHAIN=default
  - PROJECT_DIR=examples/Foo TOOLCHAIN=libcxx
  - PROJECT_DIR=examples/Foo TOOLCHAIN=clang-libstdcxx
  - PROJECT_DIR=examples/Foo TOOLCHAIN=xcode
  - PROJECT_DIR=examples/Foo TOOLCHAIN=osx-10-9
  - PROJECT_DIR=examples/Foo TOOLCHAIN=gcc
  - PROJECT_DIR=examples/Foo TOOLCHAIN=gcc-4-8
  - PROJECT_DIR=examples/Foo TOOLCHAIN=ios-nocodesign
  - PROJECT_DIR=examples/Foo TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon
  - PROJECT_DIR=examples/Foo TOOLCHAIN=analyze
  - PROJECT_DIR=examples/Foo TOOLCHAIN=sanitize-address
  - PROJECT_DIR=examples/Foo TOOLCHAIN=sanitize-leak
  - PROJECT_DIR=examples/Foo TOOLCHAIN=sanitize-thread

matrix:
  exclude:
    ### Linux excludes ###
    # https://github.com/travis-ci-tester/travis-test-clang-with-libcxx
    - os: linux
      env: PROJECT_DIR=examples/Foo TOOLCHAIN=libcxx

    # Xcode is for OSX only
    - os: linux
      env: PROJECT_DIR=examples/Foo TOOLCHAIN=xcode
    - os: linux
      env: PROJECT_DIR=examples/Foo TOOLCHAIN=osx-10-9
    - os: linux
      env: PROJECT_DIR=examples/Foo TOOLCHAIN=ios-nocodesign

    # https://github.com/travis-ci-tester/travis-test-gcc-cxx-11
    - os: linux
      env: PROJECT_DIR=examples/Foo TOOLCHAIN=gcc

    ### OSX excludes ###
    # TOOLCHAIN=gcc works fine on OSX
    - os: osx
      env: PROJECT_DIR=examples/Foo TOOLCHAIN=gcc-4-8

    # https://github.com/travis-ci-tester/travis-test-mac-clang-address-sanitizer
    - os: osx
      env: PROJECT_DIR=examples/Foo TOOLCHAIN=sanitize-address

    # Linux only
    - os: osx
      env: PROJECT_DIR=examples/Foo TOOLCHAIN=sanitize-leak
    - os: osx
      env: PROJECT_DIR=examples/Foo TOOLCHAIN=sanitize-thread

install:
  # Info about OS
  - uname -a

  # Install Python 3
  - if [[ "`uname`" == "Darwin" ]]; then brew install python3; fi

  # Install Python package 'requests'
  # 'easy_install3' is not installed by 'brew install python3' on OS X 10.9 Maverick
  - if [[ "`uname`" == "Darwin" ]]; then pip3 install requests; fi
  - if [[ "`uname`" == "Linux" ]]; then easy_install3 --user requests; fi

  # Install latest Polly toolchains and scripts
  - wget https://github.com/ruslo/polly/archive/master.zip
  - unzip master.zip
  - POLLY_ROOT="`pwd`/polly-master"
  - export PATH="${POLLY_ROOT}/bin:${PATH}"

  # Install dependencies (CMake, Android NDK)
  - install-ci-dependencies.py

  # Tune locations
  - export PATH="`pwd`/_ci/cmake/bin:${PATH}"

  # Installed if toolchain is Android (otherwise directory doesn't exist)
  - export ANDROID_NDK_r10e="`pwd`/_ci/android-ndk-r10e"

script:
  - python3 ./jenkins.py
