# Windows (https://github.com/travis-ci-tester/toolchain-table)

environment:
  global:
    # This variable used only if '--upload' added to 'jenkins.py'
    GITHUB_USER_PASSWORD:
      secure: tzWauRyJgacWahxWX5cKP+rnnczqdEXAIzP7ayUgt16GfoGKpkqa/QvDJYxLKM6Q

  matrix:

    - TOOLCHAIN: "ninja-vs-15-2017-win64-cxx17"
      PROJECT_DIR: examples\cub
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    - TOOLCHAIN: "nmake-vs-15-2017-win64-cxx17"
      PROJECT_DIR: examples\cub
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    - TOOLCHAIN: "vs-15-2017-win64-cxx17"
      PROJECT_DIR: examples\cub
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    - TOOLCHAIN: "vs-14-2015-sdk-8-1"
      PROJECT_DIR: examples\cub
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

    - TOOLCHAIN: "mingw-cxx17"
      PROJECT_DIR: examples\cub
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

    - TOOLCHAIN: "msys-cxx17"
      PROJECT_DIR: examples\cub
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

install:
  # Python 3
  - cmd: set PATH=C:\Python34-x64;C:\Python34-x64\Scripts;%PATH%

  # Install Python package 'requests', 'gitpython'
  - cmd: pip install requests
  - cmd: pip install gitpython

  # Install latest Polly toolchains and scripts
  - cmd: appveyor DownloadFile https://github.com/ruslo/polly/archive/master.zip
  - cmd: 7z x master.zip
  - cmd: set POLLY_ROOT=%cd%\polly-master

  # Install dependencies (CMake, Ninja)
  - cmd: python %POLLY_ROOT%\bin\install-ci-dependencies.py

  # Tune locations
  - cmd: set PATH=%cd%\_ci\cmake\bin;%PATH%
  - cmd: set PATH=%cd%\_ci\ninja;%PATH%

  - cmd: git submodule update --init --recursive

  # Remove entry with sh.exe from PATH to fix error with MinGW toolchain
  # (For MinGW make to work correctly sh.exe must NOT be in your path)
  # * http://stackoverflow.com/a/3870338/2288008
  - cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

  # Save git.exe in HUNTER_GIT_EXECUTABLE for upload
  # * https://docs.hunter.sh/en/latest/reference/user-variables.html#hunter-git-executable
  # Variable will be used in CMake so it's okay to use Unix style '/'
  - cmd: set HUNTER_GIT_EXECUTABLE=C:/Program Files/Git/bin/git.exe

  - cmd: set MINGW_PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin

  # MSYS2 location
  - cmd: set MSYS_PATH=C:\msys64\usr\bin

  # Visual Studio 15 2017: Mimic behavior of older versions
  - cmd: set VS150COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools

build_script:
  - cmd: python .\jenkins.py

# http://www.appveyor.com/docs/branches#white-and-blacklisting
# Exclude branch 'pkg.template'. Nothing to build there.
branches:
  except:
    - pkg.template
    - /^pr\..*/
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/
