# Windows (https://github.com/travis-ci-tester/toolchain-table)

environment:
  global:
    # This variable used only if '--upload' added to 'jenkins.py'
    GITHUB_USER_PASSWORD:
      secure: uW6WWlvCt7CRvvdO9ePjbymPcPNuV1C6HGF8u7Ey6EI=

  matrix:
    - TOOLCHAIN: "default"
      PROJECT_DIR: examples\Foo

    - TOOLCHAIN: "ninja-vs-12-2013-win64"
      PROJECT_DIR: examples\Foo

    - TOOLCHAIN: "nmake-vs-12-2013-win64"
      PROJECT_DIR: examples\Foo

    - TOOLCHAIN: "nmake-vs-12-2013"
      PROJECT_DIR: examples\Foo

    - TOOLCHAIN: "vs-10-2010"
      PROJECT_DIR: examples\Foo

    - TOOLCHAIN: "vs-11-2012"
      PROJECT_DIR: examples\Foo

    - TOOLCHAIN: "vs-12-2013-win64"
      PROJECT_DIR: examples\Foo

    - TOOLCHAIN: "vs-12-2013-xp"
      PROJECT_DIR: examples\Foo

    - TOOLCHAIN: "vs-12-2013"
      PROJECT_DIR: examples\Foo

    - TOOLCHAIN: "vs-14-2015"
      PROJECT_DIR: examples\Foo

    - TOOLCHAIN: "vs-9-2008"
      PROJECT_DIR: examples\Foo

    - TOOLCHAIN: "mingw"
      PROJECT_DIR: examples\Foo

install:
  # Python 3
  - cmd: set PATH=C:\Python34-x64;C:\Python34-x64\Scripts;%PATH%

  # Install Python package 'requests'
  - cmd: pip install requests

  # Install latest Polly toolchains and scripts
  - cmd: appveyor DownloadFile https://github.com/ruslo/polly/archive/master.zip
  - cmd: 7z x master.zip
  - cmd: set POLLY_ROOT=%cd%\polly-master

  # Install dependencies (CMake, Ninja)
  - cmd: python %POLLY_ROOT%\bin\install-ci-dependencies.py

  # Tune locations
  - cmd: set PATH=%cd%\_ci\cmake\bin;%PATH%
  - cmd: set PATH=%cd%\_ci\ninja;%PATH%

  # Remove entry with sh.exe from PATH to fix error with MinGW toolchain
  # (For MinGW make to work correctly sh.exe must NOT be in your path)
  # * http://stackoverflow.com/a/3870338/2288008
  - cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

  # Use MinGW from Qt tools because version is higher
  # * http://www.appveyor.com/docs/installed-software#qt
  - cmd: set MINGW_PATH=C:\Qt\Tools\mingw492_32\bin

  - git submodule update --init --recursive

build_script:
  - cmd: python .\jenkins.py

# http://www.appveyor.com/docs/branches#white-and-blacklisting
# Exclude branch 'pkg.template'. Nothing to build there.
branches:
  except:
    - pkg.template
